In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

%matplotlib inline

#### hh1 - Households by Type: 1940 to Present (Numbers in thousands)
Source:  Source:  U.S. Census Bureau, Decennial Census, 1940, and Current Population Survey, March and Annual Social and Economic Supplements, 1947 to 2022.										
https://www.census.gov/data/tables/time-series/demo/families/households.html

In [2]:
hh1 = pd.read_excel('../data/single_parent/census/historical_households/hh1_by_type_1940_pres.xls', skiprows=9, nrows=84)
pd.set_option('display.max_rows', None)
hh1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Male householder,Female householder,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,131202.0,84265.0,61435.0,NaN,7212.0,15618.0,NaN,46937.0,22716.0,24221.0
2,2021r,129224.0,83711.0,61288.0,NaN,6963.0,15461.0,NaN,45533.0,21674.0,23859.0
3,2021,129931.0,83907.0,61454.0,NaN,6963.0,15490.0,NaN,46024.0,21781.0,24244.0
4,2020,128451.0,83677.0,62342.0,NaN,6503.0,14832.0,NaN,44774.0,21304.0,23470.0
5,2019,128579.0,83482.0,61959.0,NaN,6480.0,15043.0,NaN,45096.0,21582.0,23515.0
6,2018,127586.0,83088.0,61241.0,NaN,6424.0,15423.0,NaN,44498.0,21017.0,23481.0
7,2017,126224.0,82827.0,60804.0,NaN,6452.0,15572.0,NaN,43396.0,20539.0,22858.0
8,2016,125819.0,82184.0,60251.0,NaN,6310.0,15622.0,NaN,43635.0,20542.0,23093.0
9,2015,124587.0,81716.0,60010.0,NaN,6162.0,15544.0,NaN,42871.0,20143.0,22728.0
10,2014s,123229.0,81353.0,59629.0,NaN,6304.0,15420.0,NaN,41877.0,19658.0,22219.0
11,2013,122459.0,80902.0,59204.0,NaN,6229.0,15469.0,NaN,41558.0,19747.0,21810.0
12,2012,121084.0,80506.0,58949.0,NaN,5888.0,15669.0,NaN,40578.0,19195.0,21383.0
13,2011r,119927.0,79539.0,58656.0,NaN,5648.0,15235.0,NaN,40388.0,18968.0,21420.0
14,2011,118682.0,78613.0,58036.0,NaN,5559.0,15019.0,NaN,40069.0,18835.0,21234.0
15,2010,117538.0,78833.0,58410.0,NaN,5580.0,14843.0,NaN,38705.0,18263.0,20442.0
16,2009,117181.0,78850.0,59118.0,NaN,5252.0,14480.0,NaN,38331.0,17694.0,20637.0
17,2008,116783.0,77873.0,58370.0,NaN,5100.0,14404.0,NaN,38910.0,17872.0,21038.0
18,2007,116011.0,78425.0,58945.0,NaN,5063.0,14416.0,NaN,37587.0,17338.0,20249.0
19,2006,114384.0,77402.0,58179.0,NaN,5130.0,14093.0,NaN,36982.0,16753.0,20230.0
20,2005,113343.0,76858.0,57975.0,NaN,4901.0,13981.0,NaN,36485.0,16543.0,19942.0
21,2004,112000.0,76217.0,57719.0,NaN,4716.0,13781.0,NaN,35783.0,16136.0,19647.0
22,2003,111278.0,75596.0,57320.0,NaN,4656.0,13620.0,NaN,35682.0,16020.0,19662.0
23,2002,109297.0,74329.0,56747.0,NaN,4438.0,13143.0,NaN,34969.0,15579.0,19390.0
24,2001e,108209.0,73767.0,56592.0,NaN,4275.0,12900.0,NaN,34442.0,15345.0,19097.0
25,2000,104705.0,72025.0,55311.0,NaN,4028.0,12687.0,NaN,32680.0,14641.0,18039.0
26,1999,103874.0,71535.0,54770.0,NaN,3976.0,12789.0,NaN,32339.0,14368.0,17971.0
27,1998,102528.0,70880.0,54317.0,NaN,3911.0,12652.0,NaN,31648.0,14133.0,17516.0
28,1997,101018.0,70241.0,53604.0,NaN,3847.0,12790.0,NaN,30777.0,13707.0,17070.0
29,1996,99627.0,69594.0,53567.0,NaN,3513.0,12514.0,NaN,30033.0,13348.0,16685.0
30,1995,98990.0,69305.0,53858.0,NaN,3226.0,12220.0,NaN,29686.0,13190.0,16496.0
31,1994,97107.0,68490.0,53171.0,NaN,2913.0,12406.0,NaN,28617.0,12462.0,16155.0
32,1993r,96426.0,68216.0,53090.0,NaN,3065.0,12061.0,NaN,28210.0,12297.0,15914.0
33,1993,96391.0,68144.0,53171.0,NaN,3026.0,11947.0,NaN,28247.0,12254.0,15993.0
34,1992,95669.0,67173.0,52457.0,NaN,3025.0,11692.0,NaN,28496.0,12428.0,16068.0
35,1991,94312.0,66322.0,52147.0,NaN,2907.0,11268.0,NaN,27990.0,12150.0,15840.0
36,1990,93347.0,66090.0,52317.0,NaN,2884.0,10890.0,NaN,27257.0,11606.0,15651.0
37,1989,92830.0,65837.0,52100.0,NaN,2847.0,10890.0,NaN,26994.0,11874.0,15120.0
38,1988a,91124.0,65204.0,51675.0,NaN,2834.0,10696.0,NaN,25919.0,11282.0,14637.0
39,1988,91066.0,65133.0,51809.0,NaN,2715.0,10608.0,NaN,25933.0,11310.0,14624.0
40,1987,89479.0,64491.0,51537.0,NaN,2510.0,10445.0,NaN,24988.0,10652.0,14336.0
41,1986,88458.0,63558.0,50933.0,NaN,2414.0,10211.0,NaN,24900.0,10648.0,14252.0
42,1985,86789.0,62706.0,50350.0,NaN,2228.0,10129.0,NaN,24082.0,10114.0,13968.0
43,1984b,85290.0,62015.0,50081.0,NaN,2038.0,9896.0,NaN,23276.0,9689.0,13587.0
44,1984,85407.0,61997.0,50090.0,NaN,2030.0,9878.0,NaN,23410.0,9752.0,13658.0
45,1983,83918.0,61393.0,49908.0,NaN,2016.0,9469.0,NaN,22525.0,9514.0,13011.0
46,1982,83527.0,61019.0,49630.0,NaN,1986.0,9403.0,NaN,22508.0,9457.0,13051.0
47,1981,82368.0,60309.0,49294.0,NaN,1933.0,9082.0,NaN,22059.0,9279.0,12780.0
48,1980c,80776.0,59550.0,49112.0,NaN,1733.0,8705.0,NaN,21226.0,8807.0,12419.0
49,1980,79108.0,58426.0,48180.0,NaN,1706.0,8540.0,NaN,20682.0,8594.0,12088.0
50,1979,77330.0,57498.0,47662.0,NaN,1616.0,8220.0,NaN,19831.0,8064.0,11767.0
51,1978,76030.0,56958.0,47357.0,NaN,1564.0,8037.0,NaN,19071.0,7811.0,11261.0
52,1977,74142.0,56472.0,47471.0,NaN,1461.0,7540.0,NaN,17669.0,6971.0,10698.0
53,1976,72867.0,56056.0,47297.0,NaN,1424.0,7335.0,NaN,16811.0,6548.0,10263.0
54,1975,71120.0,55563.0,46951.0,NaN,1485.0,7127.0,NaN,15557.0,5912.0,9645.0
55,1974,69859.0,54917.0,46787.0,NaN,1421.0,6709.0,NaN,14942.0,5654.0,9288.0
56,1973,68251.0,54264.0,46297.0,NaN,1432.0,6535.0,NaN,13986.0,5129.0,8858.0
57,1972,66676.0,53163.0,45724.0,NaN,1331.0,6108.0,NaN,13513.0,4839.0,8674.0
58,1971,64778.0,52102.0,44928.0,NaN,1254.0,5920.0,NaN,12676.0,4403.0,8273.0
59,1970,63401.0,51456.0,44728.0,NaN,1228.0,5500.0,NaN,11945.0,4063.0,7882.0
60,1969,62214.0,50729.0,44086.0,NaN,1221.0,5422.0,NaN,11485.0,3890.0,7595.0
61,1968,60813.0,50012.0,43507.0,NaN,1195.0,5310.0,NaN,10801.0,3658.0,7143.0
62,1967,59236.0,49086.0,42743.0,NaN,1190.0,5153.0,NaN,10150.0,3419.0,6731.0
63,1966,58406.0,48399.0,42263.0,NaN,1163.0,4973.0,NaN,10007.0,3299.0,6708.0
64,1965,57436.0,47838.0,41689.0,NaN,1167.0,4982.0,NaN,9598.0,3277.0,6321.0
65,1964,56149.0,47381.0,41341.0,NaN,1204.0,4836.0,NaN,8768.0,2965.0,5803.0
66,1963,55270.0,46872.0,40888.0,NaN,1295.0,4689.0,NaN,8398.0,2838.0,5560.0
67,1962,54764.0,46262.0,40404.0,NaN,1268.0,4590.0,NaN,8502.0,2932.0,5570.0
68,1961,53557.0,45383.0,39620.0,NaN,1199.0,4564.0,NaN,8174.0,2779.0,5395.0
69,1960,52799.0,44905.0,39254.0,NaN,1228.0,4422.0,NaN,7895.0,2716.0,5179.0
70,1959,51435.0,43971.0,38410.0,NaN,1285.0,4276.0,NaN,7464.0,2449.0,5015.0
71,1958,50474.0,43426.0,37911.0,NaN,1278.0,4237.0,NaN,7047.0,2329.0,4718.0
72,1957,49673.0,43262.0,37718.0,NaN,1241.0,4304.0,NaN,6411.0,2038.0,4374.0
73,1956,48902.0,42593.0,37047.0,NaN,1408.0,4138.0,NaN,6309.0,2058.0,4250.0
74,1955,47874.0,41732.0,36251.0,NaN,1328.0,4153.0,NaN,6142.0,2059.0,4083.0
75,1954,46962.0,40998.0,35926.0,NaN,1315.0,3757.0,NaN,5964.0,1925.0,4039.0
76,1953,46385.0,40540.0,35577.0,NaN,1206.0,3757.0,NaN,5845.0,1902.0,3943.0
77,1952,45538.0,40235.0,35164.0,NaN,1119.0,3952.0,NaN,5303.0,1757.0,3546.0
78,1951,44673.0,39502.0,34391.0,NaN,1154.0,3957.0,NaN,5171.0,1732.0,3439.0
79,1950,43554.0,38838.0,34075.0,NaN,1169.0,3594.0,NaN,4716.0,1668.0,3048.0
80,1949,42182.0,38080.0,33257.0,NaN,1197.0,3626.0,NaN,4102.0,1308.0,2794.0
81,1948,40532.0,36629.0,31900.0,NaN,1020.0,3709.0,NaN,3903.0,1198.0,2705.0
82,1947,39107.0,34964.0,30612.0,NaN,1129.0,3223.0,NaN,4143.0,1388.0,2755.0
83,1940d,34949.0,31491.0,26571.0,NaN,1510.0,3410.0,NaN,3458.0,1599.0,1859.0

In [3]:
#rename columns
hh1 = hh1.rename(columns = {'Unnamed: 0': 'year', 'Unnamed: 1': 'total_hh', 'Unnamed: 2': 'total_fam_hh', 'Unnamed: 3': 'married_fam_hh', 'Male householder': 'male_hh_fam_hh', 'Female householder': 'female_hh_fam_hh'})
hh1.head(2)

#drop empty columns or columns not needed
hh1 = hh1.drop(['Unnamed: 4', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10'], axis=1)

#drop prior index rows, drop original rows and keep revised
hh1 = hh1.drop(labels=[0, 3, 14, 33, 39, 44, 49]).reset_index(drop=True)

#remove extra spaces in column headers
hh1 = hh1.rename(columns=lambda x: x.strip())

# remove extra spaces over all strings
hh1 = hh1.applymap(lambda x: x.strip() if isinstance(x, str) else x)

hh1.head(2)

,year,total_hh,total_fam_hh,married_fam_hh,male_hh_fam_hh,female_hh_fam_hh
0,2022,131202.0,84265.0,61435.0,7212.0,15618.0
1,2021r,129224.0,83711.0,61288.0,6963.0,15461.0

In [4]:
hh1 = hh1.astype({'year': 'str', 'total_hh': 'int64', 'total_fam_hh': 'int64', 'married_fam_hh': 'int64', 'male_hh_fam_hh': 'int64', 'female_hh_fam_hh': 'int64'})
hh1

,year,total_hh,total_fam_hh,married_fam_hh,male_hh_fam_hh,female_hh_fam_hh
0,2022,131202,84265,61435,7212,15618
1,2021r,129224,83711,61288,6963,15461
2,2020,128451,83677,62342,6503,14832
3,2019,128579,83482,61959,6480,15043
4,2018,127586,83088,61241,6424,15423
5,2017,126224,82827,60804,6452,15572
6,2016,125819,82184,60251,6310,15622
7,2015,124587,81716,60010,6162,15544
8,2014s,123229,81353,59629,6304,15420
9,2013,122459,80902,59204,6229,15469
10,2012,121084,80506,58949,5888,15669
11,2011r,119927,79539,58656,5648,15235
12,2010,117538,78833,58410,5580,14843
13,2009,117181,78850,59118,5252,14480
14,2008,116783,77873,58370,5100,14404
15,2007,116011,78425,58945,5063,14416
16,2006,114384,77402,58179,5130,14093
17,2005,113343,76858,57975,4901,13981
18,2004,112000,76217,57719,4716,13781
19,2003,111278,75596,57320,4656,13620
20,2002,109297,74329,56747,4438,13143
21,2001e,108209,73767,56592,4275,12900
22,2000,104705,72025,55311,4028,12687
23,1999,103874,71535,54770,3976,12789
24,1998,102528,70880,54317,3911,12652
25,1997,101018,70241,53604,3847,12790
26,1996,99627,69594,53567,3513,12514
27,1995,98990,69305,53858,3226,12220
28,1994,97107,68490,53171,2913,12406
29,1993r,96426,68216,53090,3065,12061
30,1992,95669,67173,52457,3025,11692
31,1991,94312,66322,52147,2907,11268
32,1990,93347,66090,52317,2884,10890
33,1989,92830,65837,52100,2847,10890
34,1988a,91124,65204,51675,2834,10696
35,1987,89479,64491,51537,2510,10445
36,1986,88458,63558,50933,2414,10211
37,1985,86789,62706,50350,2228,10129
38,1984b,85290,62015,50081,2038,9896
39,1983,83918,61393,49908,2016,9469
40,1982,83527,61019,49630,1986,9403
41,1981,82368,60309,49294,1933,9082
42,1980c,80776,59550,49112,1733,8705
43,1979,77330,57498,47662,1616,8220
44,1978,76030,56958,47357,1564,8037
45,1977,74142,56472,47471,1461,7540
46,1976,72867,56056,47297,1424,7335
47,1975,71120,55563,46951,1485,7127
48,1974,69859,54917,46787,1421,6709
49,1973,68251,54264,46297,1432,6535
50,1972,66676,53163,45724,1331,6108
51,1971,64778,52102,44928,1254,5920
52,1970,63401,51456,44728,1228,5500
53,1969,62214,50729,44086,1221,5422
54,1968,60813,50012,43507,1195,5310
55,1967,59236,49086,42743,1190,5153
56,1966,58406,48399,42263,1163,4973
57,1965,57436,47838,41689,1167,4982
58,1964,56149,47381,41341,1204,4836
59,1963,55270,46872,40888,1295,4689
60,1962,54764,46262,40404,1268,4590
61,1961,53557,45383,39620,1199,4564
62,1960,52799,44905,39254,1228,4422
63,1959,51435,43971,38410,1285,4276
64,1958,50474,43426,37911,1278,4237
65,1957,49673,43262,37718,1241,4304
66,1956,48902,42593,37047,1408,4138
67,1955,47874,41732,36251,1328,4153
68,1954,46962,40998,35926,1315,3757
69,1953,46385,40540,35577,1206,3757
70,1952,45538,40235,35164,1119,3952
71,1951,44673,39502,34391,1154,3957
72,1950,43554,38838,34075,1169,3594
73,1949,42182,38080,33257,1197,3626
74,1948,40532,36629,31900,1020,3709
75,1947,39107,34964,30612,1129,3223
76,1940d,34949,31491,26571,1510,3410

In [5]:
#locate additional letters in year column
hh1_by_type = hh1[hh1['year'].str.match('\d{4}[a-zA-Z]?', na=False)]
#extract only the year
hh1_by_type['year'] = hh1_by_type['year'].str.extract('(\d{4})', expand=False).astype(int)
#sort by descending
hh1_by_type = hh1_by_type.sort_values('year', ascending=False)

hh1_by_type

,year,total_hh,total_fam_hh,married_fam_hh,male_hh_fam_hh,female_hh_fam_hh
0,2022,131202,84265,61435,7212,15618
1,2021,129224,83711,61288,6963,15461
2,2020,128451,83677,62342,6503,14832
3,2019,128579,83482,61959,6480,15043
4,2018,127586,83088,61241,6424,15423
5,2017,126224,82827,60804,6452,15572
6,2016,125819,82184,60251,6310,15622
7,2015,124587,81716,60010,6162,15544
8,2014,123229,81353,59629,6304,15420
9,2013,122459,80902,59204,6229,15469
10,2012,121084,80506,58949,5888,15669
11,2011,119927,79539,58656,5648,15235
12,2010,117538,78833,58410,5580,14843
13,2009,117181,78850,59118,5252,14480
14,2008,116783,77873,58370,5100,14404
15,2007,116011,78425,58945,5063,14416
16,2006,114384,77402,58179,5130,14093
17,2005,113343,76858,57975,4901,13981
18,2004,112000,76217,57719,4716,13781
19,2003,111278,75596,57320,4656,13620
20,2002,109297,74329,56747,4438,13143
21,2001,108209,73767,56592,4275,12900
22,2000,104705,72025,55311,4028,12687
23,1999,103874,71535,54770,3976,12789
24,1998,102528,70880,54317,3911,12652
25,1997,101018,70241,53604,3847,12790
26,1996,99627,69594,53567,3513,12514
27,1995,98990,69305,53858,3226,12220
28,1994,97107,68490,53171,2913,12406
29,1993,96426,68216,53090,3065,12061
30,1992,95669,67173,52457,3025,11692
31,1991,94312,66322,52147,2907,11268
32,1990,93347,66090,52317,2884,10890
33,1989,92830,65837,52100,2847,10890
34,1988,91124,65204,51675,2834,10696
35,1987,89479,64491,51537,2510,10445
36,1986,88458,63558,50933,2414,10211
37,1985,86789,62706,50350,2228,10129
38,1984,85290,62015,50081,2038,9896
39,1983,83918,61393,49908,2016,9469
40,1982,83527,61019,49630,1986,9403
41,1981,82368,60309,49294,1933,9082
42,1980,80776,59550,49112,1733,8705
43,1979,77330,57498,47662,1616,8220
44,1978,76030,56958,47357,1564,8037
45,1977,74142,56472,47471,1461,7540
46,1976,72867,56056,47297,1424,7335
47,1975,71120,55563,46951,1485,7127
48,1974,69859,54917,46787,1421,6709
49,1973,68251,54264,46297,1432,6535
50,1972,66676,53163,45724,1331,6108
51,1971,64778,52102,44928,1254,5920
52,1970,63401,51456,44728,1228,5500
53,1969,62214,50729,44086,1221,5422
54,1968,60813,50012,43507,1195,5310
55,1967,59236,49086,42743,1190,5153
56,1966,58406,48399,42263,1163,4973
57,1965,57436,47838,41689,1167,4982
58,1964,56149,47381,41341,1204,4836
59,1963,55270,46872,40888,1295,4689
60,1962,54764,46262,40404,1268,4590
61,1961,53557,45383,39620,1199,4564
62,1960,52799,44905,39254,1228,4422
63,1959,51435,43971,38410,1285,4276
64,1958,50474,43426,37911,1278,4237
65,1957,49673,43262,37718,1241,4304
66,1956,48902,42593,37047,1408,4138
67,1955,47874,41732,36251,1328,4153
68,1954,46962,40998,35926,1315,3757
69,1953,46385,40540,35577,1206,3757
70,1952,45538,40235,35164,1119,3952
71,1951,44673,39502,34391,1154,3957
72,1950,43554,38838,34075,1169,3594
73,1949,42182,38080,33257,1197,3626
74,1948,40532,36629,31900,1020,3709
75,1947,39107,34964,30612,1129,3223
76,1940,34949,31491,26571,1510,3410

In [6]:
hh1_by_type.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 77 entries, 0 to 76
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              77 non-null     int32
 1   total_hh          77 non-null     int64
 2   total_fam_hh      77 non-null     int64
 3   married_fam_hh    77 non-null     int64
 4   male_hh_fam_hh    77 non-null     int64
 5   female_hh_fam_hh  77 non-null     int64
dtypes: int32(1), int64(5)
memory usage: 3.9 KB

In [ ]:
hh1_by_type.to_csv('../data/single_parent/census/historical_households/hh1_by_type.csv', index = False)